[package]
name = "advent_of_code_2016"
version = "0.1.0"
authors = ["Galen Elias <gelias@gmail.com>"]

[dependencies]
clap = "*"
regex = "*"
md5 = "*"
lazy_static = "*"
permutohedron = "*"

[[bin]]
name = "aoc"
path = "src/main.rs"